import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    paddingTop: 0,
    paddingHorizontal: 0,
    alignItems: "center",
    backgroundColor: "#F4F7FC",
    minHeight: "100%",
  },

  topBar: {
    width: "100%",
    paddingVertical: 18,
    paddingHorizontal: 20,
    backgroundColor: "#1C743C",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  topBarTitle: {
    color: "#fff",
    fontSize: 19,
    fontWeight: "600",
    textAlign: "center",
    flex: 1,
    marginHorizontal: 15,
  },

  card: {
    width: "90%",
    maxWidth: 400,
    backgroundColor: "#fff",
    padding: 20,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 5,
    alignItems: "center",
    marginTop: 25,
    borderRadius: 12,
    borderWidth: 0,
  },
  avatar: {
    width: 130,
    height: 130,
    marginBottom: 15,
    resizeMode: "cover",
    backgroundColor: "#E8F5E9",
    borderRadius: 65,
    borderWidth: 3,
    borderColor: "#4CAF50",
  },
  info: {
    alignItems: "center",
    marginBottom: 15,
  },
  name: {
    fontSize: 24,
    fontWeight: "700",
    marginBottom: 8,
    color: "#212121",
  },
  small: {
    fontSize: 15,
    color: "#616161",
    marginBottom: 3,
  },

  button: {
    backgroundColor: "#4CAF50",
    paddingVertical: 12,
    paddingHorizontal: 20,
    marginTop: 15,
    borderRadius: 8,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  buttonText: {
    color: "#fff",
    fontWeight: "600",
    textAlign: "center",
    fontSize: 16,
  },
  
  secondaryButton: {
    backgroundColor: "#9E9E9E",
    paddingVertical: 12,
    paddingHorizontal: 20,
    marginTop: 15,
    borderRadius: 8,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },

  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.4)",
    padding: 20,
  },
  modalContent: {
    width: "100%",
    maxWidth: 450,
    backgroundColor: "#fff",
    padding: 25,
    borderRadius: 12,
    borderWidth: 0,
    elevation: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 20,
    color: "#212121",
    textAlign: "center",
  },

  input: {
    borderWidth: 1,
    borderColor: "#E0E0E0",
    backgroundColor: "#F9F9F9",
    paddingHorizontal: 15,
    paddingVertical: 12,
    marginBottom: 10,
    borderRadius: 8,
    fontSize: 16,
    color: "#333",
  },

  imageButton: {
    backgroundColor: "#66BB6A",
    paddingVertical: 12,
    paddingHorizontal: 18,
    marginBottom: 15,
    borderRadius: 8,
    alignSelf: "center",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  imageButtonText: {
    color: "#fff",
    fontWeight: "600",
    textAlign: "center",
    fontSize: 16,
  },

  previewImage: {
    width: 120,
    height: 120,
    marginBottom: 15,
    resizeMode: "cover",
    backgroundColor: "#E8F5E9",
    borderRadius: 60,
    borderWidth: 3,
    borderColor: "#4CAF50",
    alignSelf: "center",
  },
});
