import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    paddingTop: 0,
    paddingHorizontal: 0,
    alignItems: "center",
    backgroundColor: "#f0f7f3",
    minHeight: "100%",
  },
  topBar: {
    width: "100%",
    paddingVertical: 16,
    paddingHorizontal: 20,
    backgroundColor: "#228B22",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  topBarTitle: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "700",
    textAlign: "center",
    flex: 1,
    marginHorizontal: 10,
  },
  card: {
    width: 360,
    backgroundColor: "#fff",
    padding: 18,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    alignItems: "center",
    marginTop: 16,
    borderColor: "#cde9d6",
    borderWidth: 1,
  },
  avatar: {
    width: 120,
    height: 120,
    marginBottom: 12,
    resizeMode: "cover",
    backgroundColor: "#e9f5ee",
  },
  info: {
    alignItems: "center",
    marginBottom: 12,
  },
  name: {
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 6,
    color: "#2e5d34",
  },
  small: {
    fontSize: 14,
    color: "#4d6b52",
  },
  button: {
    backgroundColor: "#3a8d49",
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginTop: 8,
  },
  buttonText: {
    color: "#fff",
    fontWeight: "600",
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.35)",
    padding: 16,
  },
  modalContent: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: "#fff",
    padding: 18,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 12,
    color: "#2e5d34",
  },
  input: {
    borderWidth: 1,
    borderColor: "#b5d6b9",
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 8,
  },
  imageButton: {
    backgroundColor: "#3a8d49",
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginBottom: 8,
  },
  imageButtonText: {
    color: "#fff",
    fontWeight: "600",
    textAlign: "center",
  },
  previewImage: {
    width: 100,
    height: 100,
    marginBottom: 8,
    resizeMode: "cover",
    backgroundColor: "#e9f5ee",
  },
});
